// AUTO-GENERATED from src/dsp/ReverbParameters.h by scripts/generate_params.js
// Do not edit this file by hand — run `npm run gen:params` to regenerate.

// Parameter spec + display formatting for the UI.
// The C++ header owns the engine values; this is purely for rendering labels/readouts.

export type Scale = "linear" | "indexed" | "quadratic" | "exponential" | "squareRoot";

export interface ParamSpec {
  id: string;
  min: number;
  max: number;
  def: number;
  postOffset: number;
  displayMultiply: number;
  scale: Scale;
  displayInvert: boolean;
  unit: string;
  name: string;
  description: string;
}

const P = (
  id: string, min: number, max: number, def: number, postOffset: number,
  displayMultiply: number, scale: Scale, displayInvert: boolean, unit: string, name: string, description: string,
): ParamSpec => ({ id, min, max, def, postOffset, displayMultiply, scale, displayInvert, unit, name, description });

export const PARAMS: ParamSpec[] = [
  P("reverb_dry_wet", 0.0, 1.0, 0.25, 0.0, 100.0, "linear", false, "%", "Reverb Mix", "Balance between dry and wet signal"),
  P("reverb_decay_time", -6.0, 6.0, 0.0, 0.0, 1.0, "exponential", false, " secs", "Reverb Decay Time", "How long the reverb tail lasts"),
  P("reverb_pre_low_cutoff", 0.0, 128.0, 0.0, 0.0, 1.0, "linear", false, " semitones", "Remove Lows", "High-pass filter before reverb. Removes low frequencies from the reverb input"),
  P("reverb_pre_high_cutoff", 0.0, 128.0, 110.0, 0.0, 1.0, "linear", false, " semitones", "Remove Highs", "Low-pass filter before reverb. Removes high frequencies from the reverb input"),
  P("reverb_low_shelf_cutoff", 0.0, 128.0, 0.0, 0.0, 1.0, "linear", false, " semitones", "Low Freq", "Cutoff frequency for the low shelf EQ in the reverb tail"),
  P("reverb_low_shelf_gain", -6.0, 0.0, 0.0, 0.0, 1.0, "linear", false, " dB", "Low Gain", "Gain adjustment for low frequencies in the reverb tail"),
  P("reverb_high_shelf_cutoff", 0.0, 128.0, 90.0, 0.0, 1.0, "linear", false, " semitones", "High Freq", "Cutoff frequency for the high shelf EQ in the reverb tail"),
  P("reverb_high_shelf_gain", -6.0, 0.0, -1.0, 0.0, 1.0, "linear", false, " dB", "High Gain", "Gain adjustment for high frequencies in the reverb tail"),
  P("reverb_delay", 0.0, 0.3, 0.0, 0.0, 1.0, "linear", false, " secs", "Reverb Delay", "Pre-delay before the reverb starts"),
  P("reverb_size", 0.0, 1.0, 0.5, 0.0, 100.0, "linear", false, "%", "Reverb Size", "Size of the virtual room"),
  P("reverb_chorus_amount", 0.0, 1.0, 0.223607, 0.0, 100.0, "quadratic", false, "%", "Reverb Chorus Amount", "Modulation depth for chorus effect on the reverb tail"),
  P("reverb_chorus_frequency", -8.0, 3.0, -2.0, 0.0, 1.0, "exponential", false, " Hz", "Reverb Chorus Frequency", "Speed of the chorus modulation"),
  P("reverb_stereo_width", 0.0, 1.0, 1.0, 0.0, 100.0, "linear", false, "%", "Reverb Stereo Width", "Stereo spread of the reverb output"),
];

export const PARAM_BY_ID: Record<string, ParamSpec> = Object.fromEntries(
  PARAMS.map((p) => [p.id, p]),
);

// Mirror of value_bridge.h::skewValue — maps an engine (raw) value to its
// human display magnitude before applying displayMultiply/postOffset.
function skew(spec: ParamSpec, value: number): number {
  switch (spec.scale) {
    case "quadratic":
      return value * value;
    case "exponential":
      return spec.displayInvert ? 1 / Math.pow(2, value) : Math.pow(2, value);
    case "squareRoot":
      return Math.sqrt(value);
    default:
      return value;
  }
}

// Format a slider's scaled (raw) value the way vial displays it.
export function formatValue(id: string, scaled: number): string {
  const spec = PARAM_BY_ID[id];
  if (!spec) return scaled.toFixed(2);
  const display = spec.displayMultiply * skew(spec, scaled) + spec.postOffset;
  const decimals = Math.abs(display) >= 100 ? 0 : Math.abs(display) >= 10 ? 1 : 2;
  const rounded = parseFloat(display.toFixed(decimals)); // trims trailing zeros (25.0 -> 25)
  return `${rounded}${spec.unit}`;
}
