#!/usr/bin/env node
/**
 * Generate ui/src/params.ts from src/dsp/ReverbParameters.h.
 *
 * The C++ header is the single source of truth for parameter ranges, defaults,
 * and scales. This script parses the constexpr kParams array and emits the
 * matching TypeScript file so the UI stays in sync automatically.
 *
 * Usage:
 *   node scripts/generate_params.js [--check]
 *
 * With --check, exits non-zero if the generated file differs from what's on
 * disk (useful for CI to catch drift).
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const HEADER = resolve(ROOT, "src/dsp/ReverbParameters.h");
const OUTPUT = resolve(ROOT, "ui/src/params.ts");

const SCALE_MAP = {
  "Scale::Linear": "linear",
  "Scale::Indexed": "indexed",
  "Scale::Quadratic": "quadratic",
  "Scale::Exponential": "exponential",
  "Scale::SquareRoot": "squareRoot",
};

function parseParams(headerText) {
  const m = headerText.match(
    /inline constexpr std::array<ParamSpec,\s*\d+>\s*kParams\s*\{\s*\{([\s\S]*?)\}\s*\};/
  );
  if (!m) throw new Error(`Could not find kParams array in ${HEADER}`);
  const body = m[1];

  const entryRe =
    /\{\s*"([^"]+)"\s*,\s*([^,]+)\s*,\s*([^,]+)\s*,\s*([^,]+)\s*,\s*([^,]+)\s*,\s*([^,]+)\s*,\s*(Scale::\w+)\s*,\s*(true|false)\s*,\s*"([^"]*)"\s*,\s*"([^"]*)"\s*,\s*"([^"]*)"\s*\}/g;

  const params = [];
  let em;
  while ((em = entryRe.exec(body)) !== null) {
    params.push({
      id: em[1],
      min: em[2].trim().replace(/f$/, ""),
      max: em[3].trim().replace(/f$/, ""),
      def: em[4].trim().replace(/f$/, ""),
      postOffset: em[5].trim().replace(/f$/, ""),
      displayMultiply: em[6].trim().replace(/f$/, ""),
      scale: SCALE_MAP[em[7]],
      displayInvert: em[8],
      unit: em[9],
      name: em[10],
      description: em[11],
    });
  }
  if (!params.length) throw new Error("No param entriess parsed from kParams");
  return params;
}

function emit(params) {
  const lines = [
    `// AUTO-GENERATED from src/dsp/ReverbParameters.h by scripts/generate_params.js`,
    `// Do not edit this file by hand — run \`npm run gen:params\` to regenerate.`,
    ``,
    `// Parameter spec + display formatting for the UI.`,
    `// The C++ header owns the engine values; this is purely for rendering labels/readouts.`,
    ``,
    `export type Scale = "linear" | "indexed" | "quadratic" | "exponential" | "squareRoot";`,
    ``,
    `export interface ParamSpec {`,
    `  id: string;`,
    `  min: number;`,
    `  max: number;`,
    `  def: number;`,
    `  postOffset: number;`,
    `  displayMultiply: number;`,
    `  scale: Scale;`,
    `  displayInvert: boolean;`,
    `  unit: string;`,
    `  name: string;`,
    `  description: string;`,
    `}`,
    ``,
    `const P = (`,
    `  id: string, min: number, max: number, def: number, postOffset: number,`,
    `  displayMultiply: number, scale: Scale, displayInvert: boolean, unit: string, name: string, description: string,`,
    `): ParamSpec => ({ id, min, max, def, postOffset, displayMultiply, scale, displayInvert, unit, name, description });`,
    ``,
    `export const PARAMS: ParamSpec[] = [`,
  ];

  for (const p of params) {
    lines.push(
      `  P("${p.id}", ${p.min}, ${p.max}, ${p.def}, ${p.postOffset}, ` +
        `${p.displayMultiply}, "${p.scale}", ${p.displayInvert}, ` +
        `"${p.unit}", "${p.name}", "${p.description}"),`
    );
  }

  lines.push(
    `];`,
    ``,
    `export const PARAM_BY_ID: Record<string, ParamSpec> = Object.fromEntries(`,
    `  PARAMS.map((p) => [p.id, p]),`,
    `);`,
    ``,
    `// Mirror of value_bridge.h::skewValue — maps an engine (raw) value to its`,
    `// human display magnitude before applying displayMultiply/postOffset.`,
    `function skew(spec: ParamSpec, value: number): number {`,
    `  switch (spec.scale) {`,
    `    case "quadratic":`,
    `      return value * value;`,
    `    case "exponential":`,
    `      return spec.displayInvert ? 1 / Math.pow(2, value) : Math.pow(2, value);`,
    `    case "squareRoot":`,
    `      return Math.sqrt(value);`,
    `    default:`,
    `      return value;`,
    `  }`,
    `}`,
    ``,
    `// Format a slider's scaled (raw) value the way vial displays it.`,
    `export function formatValue(id: string, scaled: number): string {`,
    `  const spec = PARAM_BY_ID[id];`,
    `  if (!spec) return scaled.toFixed(2);`,
    `  const display = spec.displayMultiply * skew(spec, scaled) + spec.postOffset;`,
    `  const decimals = Math.abs(display) >= 100 ? 0 : Math.abs(display) >= 10 ? 1 : 2;`,
    `  const rounded = parseFloat(display.toFixed(decimals)); // trims trailing zeros (25.0 -> 25)`,
    `  return \`\${rounded}\${spec.unit}\`;`,
    `}`,
    ``
  );

  return lines.join("\n");
}

function main() {
  const check = process.argv.includes("--check");

  const headerText = readFileSync(HEADER, "utf-8");
  const params = parseParams(headerText);
  const generated = emit(params);

  if (check) {
    if (existsSync(OUTPUT) && readFileSync(OUTPUT, "utf-8") === generated) {
      console.log(`params.ts is up to date (${params.length} params)`);
      process.exit(0);
    }
    console.log("params.ts is out of date — run `npm run gen:params` to regenerate");
    process.exit(1);
  }

  writeFileSync(OUTPUT, generated);
  console.log(`Generated ${OUTPUT} (${params.length} params)`);
}

main();
